#  This file is part of Collaborative Software Initiative Feed Handlers (CSI FH).
# 
#  CSI FH is free software: you can redistribute it and/or modify it under the terms of the
#  GNU General Public License as published by the Free Software Foundation, either version 3
#  of the License, or (at your option) any later version.
#  
#  CSI FH is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
#  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with CSI FH.  If not, see <http://www.gnu.org/licenses/>.

# --------------------------------------------------
# Top of the source tree
# --------------------------------------------------
TOP = ../../..

# --------------------------------------------------
# Main makefile include
# --------------------------------------------------

include $(TOP)/build/defs.mk

# --------------------------------------------------
# Set up some necessary paths, filenames, etc.
# --------------------------------------------------

INCLDIRS	= common mgmt mgmt/lib mgmt/lib/admin feeds/shared/config feeds/shared/lookup_tables
LIB 		= $(LIBDIR)/libfhlh.a

# --------------------------------------------------
# Library building include
# --------------------------------------------------

include $(TOP)/build/library.mk
