#  Copyright (C) 2008, 2009, 2010 The Collaborative Software Foundation.
#
#  This file is part of FeedHandlers (FH).
#
#  FH is free software: you can redistribute it and/or modify it under the terms of the
#  GNU Lesser General Public License as published by the Free Software Foundation, either version 3
#  of the License, or (at your option) any later version.
#
#  FH is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
#  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with FH.  If not, see <http://www.gnu.org/licenses/>.

# --------------------------------------------------
# Top of the source tree
# --------------------------------------------------
TOP = ../../..

# --------------------------------------------------
# Main makefile include
# --------------------------------------------------

include $(TOP)/build/defs.mk

# --------------------------------------------------
# Set up some necessary paths, filenames, etc.
# --------------------------------------------------

INCLDIRS	= common mgmt mgmt/lib mgmt/lib/admin feeds/shared/config
LIB 		= $(LIBDIR)/libfhlookup.a

# --------------------------------------------------
# Library building include
# --------------------------------------------------

include $(TOP)/build/library.mk
