#include "fh_log.h"
#include "fh_arca_headers.h"
#include "fh_arcatrade_revision.h"
#include "fh_feed_group.h"

#define ARCA_CONFIG_FILE "arcatrade/etc/arcatrade.conf"
#define ARCA_PLUGIN_DIR  "arcatrade/plugins"

/******************************************************************************************/
/* functions that specialize shared arca feeds                                            */
/******************************************************************************************/

/*! \brief Dump revision and build information
 *
 *  \param version feed handler version number
 */
void fh_arca_version_info(int version)
{
    FH_LOG(MGMT, STATE, ("---------------------------------------------------------"));
    FH_LOG(MGMT, STATE, ("Starting Arca Multicast version %d", version));
    FH_LOG(MGMT, STATE, ("---------------------------------------------------------"));
    FH_LOG(MGMT, STATE, ("  > Generated by %s on host %s:", BUILD_USER, BUILD_HOST));
    FH_LOG(MGMT, STATE, ("    - Architecture     : %s", BUILD_ARCH));
    FH_LOG(MGMT, STATE, ("    - Kernel version   : %s", BUILD_KVER));
    FH_LOG(MGMT, STATE, ("    - Build date       : %s", BUILD_DATE));
    FH_LOG(MGMT, STATE, ("    - Git URL          : %s", BUILD_URL));
    FH_LOG(MGMT, STATE, ("    - Git Revision     : %s", BUILD_REV));
    FH_LOG(MGMT, STATE, ("---------------------------------------------------------"));
};
/* trade feed doesnt support fast compaction; It has no concept of orders or firms*/
/*! \brief opportunity to over ride the configuration before it is applied
 *
 *  \param process maps that contain the configuration
 */
inline void chk_cfg(struct process_maps *p_map)
{
    int ix = 0;

    p_map->max_firms = 0;
    p_map->max_orders = 0;
    for(ix=0;ix<p_map->line_count;ix++)
    {
        p_map->groups[ix]->fast_mode = 0;
    }
};
/*! \brief opportunity to over ride the configuration before it is applied
 *
 *  \param process maps that contain the configuration
 */
inline char* get_build_date()
{
    return BUILD_DATE;
};
/*! \brief get the build date for this code base
 *
 *  \param None
 */
inline char* get_build_rev()
{
    return BUILD_REV;
};
/*! \brief get the configuration path for this feed handler
 *
 *  \param None
 */
inline char* get_config_path()
{
    return ARCA_CONFIG_FILE;
};
/*! \brief get the plugin directory for this feed handler
 *
 *  \param None
 */
inline char* get_plugin_dir_name()
{
    return ARCA_PLUGIN_DIR;
};
