/*
 * This file is part of Collaborative Software Initiative Feed Handlers (CSI FH).
 *
 * CSI FH is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 * 
 * CSI FH is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with CSI FH.  If not, see <http://www.gnu.org/licenses/>.
 */

/* FH headers */
#include "fh_info.h"
#include "fh_log.h"

/*
 * Log detailed version and build information at the "STATE" log level
 */
void fh_info_version_msg(const fh_info_build_t *info)
{
    FH_LOG(CSI, STATE, ("---------------------------------------------------------"));
    FH_LOG(CSI, STATE, ("Starting %s version %d", info->name, info->version));
    FH_LOG(CSI, STATE, ("---------------------------------------------------------"));
    FH_LOG(CSI, STATE, ("  > Generated by %s@%s:", info->build_user, info->build_host));
    FH_LOG(CSI, STATE, ("    - Architecture     : %s",     info->build_arch));
    FH_LOG(CSI, STATE, ("    - Kernel version   : %s",     info->build_kernel));
    FH_LOG(CSI, STATE, ("    - Build date       : %s",     info->build_date));
    FH_LOG(CSI, STATE, ("    - Git URL          : %s",     info->build_svn_url));
    FH_LOG(CSI, STATE, ("    - Git Revision     : %s",     info->build_svn_rev));
    FH_LOG(CSI, STATE, ("---------------------------------------------------------"));
}
