#include "fh_log.h"
#include "fh_arca_headers.h"
#include "fh_arca_revision.h"

#define ARCA_CONFIG_FILE "arca/etc/arca.conf"
#define ARCA_PLUGIN_DIR  "arca/plugins"

/******************************************************************************************/
/* functions that specialize shared arca feeds                                            */
/******************************************************************************************/

/*! \brief Dump revision and build information
 *
 *  \param version feed handler version number
 */
void fh_arca_version_info(int version)
{
    FH_LOG(MGMT, STATE, ("---------------------------------------------------------"));
    FH_LOG(MGMT, STATE, ("Starting Arca Multicast version %d", version));
    FH_LOG(MGMT, STATE, ("---------------------------------------------------------"));
    FH_LOG(MGMT, STATE, ("  > Generated by %s on host %s:", BUILD_USER, BUILD_HOST));
    FH_LOG(MGMT, STATE, ("    - Architecture     : %s", BUILD_ARCH));
    FH_LOG(MGMT, STATE, ("    - Kernel version   : %s", BUILD_KVER));
    FH_LOG(MGMT, STATE, ("    - Build date       : %s", BUILD_DATE));
    FH_LOG(MGMT, STATE, ("    - Git URL          : %s", BUILD_URL));
    FH_LOG(MGMT, STATE, ("    - Git Revision     : %s", BUILD_REV));
    FH_LOG(MGMT, STATE, ("---------------------------------------------------------"));
};
/*! \brief opportunity to over ride the configuration before it is applied
 *
 *  \param process maps that contain the configuration
 */
inline void chk_cfg(struct process_maps *p_map)
{
    /* suppress unused parameter warnings */
    if (p_map) {}
    /* otherwise do nothing; it is the superset*/
}
/*! \brief get the build date for this code base
 *
 *  \param None
 */
inline char* get_build_date()
{
    return BUILD_DATE;
}
/*! \brief get the build revision for this code base
 *
 *  \param None
 */
inline char* get_build_rev()
{
    return BUILD_REV;
};
/*! \brief get the configuration path for this feed handler
 *
 *  \param None
 */
inline char* get_config_path()
{
    return ARCA_CONFIG_FILE;
};
/*! \brief get the plugin directory for this feed handler
 *
 *  \param None
 */
inline char* get_plugin_dir_name()
{
    return ARCA_PLUGIN_DIR;
};
